### ISSUE TITLE
Assign alias to distribution after certificate assigned?

### ISSUE THREAD

**Issue by KristanMcDonald** [pfulop/serverless-cloudfront-distribution-certificate#13]
Caveat: I'm not sure I'm using this right, however..

I have a serverless cf script that's creating a cloudfront dist for serving an S3 bucket using a custom domain.

The plugin works perfectly, requests the cert and adds it to my distribution after the rest of the stack runs and creates it. However, to use the distribution, I need to add my custom domain as a CNAME alias to the distribution.

I can't do it in the cloud formation script for the distribution, because I don't know the ARN of the certificate, and without that it won't accept the CNAME as an alias.

So the net result is I have a cloudfront distribution with a custom SSL cert, but the distribution itself is only accepting <id>.cloudfront.net requests. I can manually add the CNAME afterwards... But that seems to defeat the point.

I don't think it's much to add to attach the CNAME, I'd be happy to write it and do a PR.. But equally I could be missing something obvious!

**Comment by pfulop** [comment]
Hi,

To be honest I moved away from the AWS stack (at least for the frontend), so I don't actively use this package anymore and I am just maintaining it and reviewing PRs.

However, I checked one of my old projects where I was using it and you do have to have cloudfront distribution specified in your config and serverless supports alias directive there:

```yaml
 Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: "StaticSiteBucketOrigin"
          ViewerProtocolPolicy: "redirect-to-https"
          MaxTTL: 31536000 # one year
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
        Enabled: true
        PriceClass: "PriceClass_100"
        HttpVersion: "http2"
        IPV6Enabled: true
        Aliases:
          - ${self:provider.domain} <-------------------- HERE
        Origins:
          - Id: "StaticSiteBucketOrigin"
            DomainName: !GetAtt StaticSite.DomainName
            S3OriginConfig: {}
```

Is this what you were missing? 

If I am missing something in your post just let me know.
