### ISSUE TITLE
Error: Can't find hostedzone

### ISSUE THREAD

**Issue by garbit** [pfulop/serverless-cloudfront-distribution-certificate#18]
I have the following config:

```
service: my-stack

frameworkVersion: "3"

plugins:
  - serverless-cloudfront-distribution-certificate

provider:
  name: aws
  stage: dev
  region: us-east-1

custom:
  bucketName: my-stack-dev
  dashboardRoute53:
    hostedZoneId: Z0XXXXXXXXXXXXXXXX
    recordName: app.my-domain.com
  cfdDomain:
    domainNames:
      - "app.my-domain.com"
    cloudFront: CloudFrontDistribution
    retries: 5
    hostedZoneId: Z0XXXXXXXXXXXXXXXX
    enabled: true
```

```package.json
{
  "name": "my-app",
  "description": "",
  "version": "0.1.0",
  "dependencies": {},
  "devDependencies": {
    "serverless-cloudfront-distribution-certificate": "0.0.8"
  }
}
```

When I run this I get "Can't find hostedZone".

Error:
```bash
sls deploy
Running "serverless" from node_modules

Deploying my-stack to stage dev (us-east-1)
Multiple domains specified
Checking: app.my-domain.com
Found existing certificate: arn:aws:acm:us-east-1:[hidden]:certificate/[hidden]
Looking for validation resource records...
Validating certificate
_49XXXXXXXXXXXXXXXXXXXXX.app.my-domain.com
Getting hosted zone id
(my console log - see below)
my-domain.com [ 'com', 'my-domain' ] 2 (length 2)

✖ Stack my-stack-dev failed to deploy (3s)
Environment: darwin, node 18.16.1, framework 3.34.0 (local) 3.35.2v (global), plugin 6.2.3, SDK 4.3.2
Credentials: Local, "[my-profile]" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Can't find hostedzone
    at ServerlessCloudfrontDistributionCertificate.<anonymous> (node_modules/serverless-cloudfront-distribution-certificate/dist/index.js:107:27)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/serverless-cloudfront-distribution-certificate/dist/index.js:4:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I've looked in the `serverless-cloudfront-distribution-certificate/dist` folder and added a console.log(hostedZone) (line 173: findHostedZoneId function):

```javascript
findHostedZoneId(domain) {
        return __awaiter(this, void 0, void 0, function* () {
            this.serverless.cli.log(`Getting hosted zone id`);
            const zones = yield this.getHostedZones();
            const domainNameReverse = domain
                .replace(/\.$/, "")
                .split(".")
                .reverse();
            const targetHostedZone = zones.filter((hostedZone) => {
                console.log(hostedZone) <- this has values
                const zoneName = hostedZone.Name.replace(/\.$/, "");
                const hostedZoneNameReverse = zoneName.split(".").reverse();
                console.log(zoneName, hostedZoneNameReverse, hostedZoneNameReverse.length) <- hostedZoneNameReverse.length = 2 ["com", "my-domain"]
                if (domainNameReverse.length === 1 ||
                    domainNameReverse.length >= hostedZoneNameReverse.length) {
                    return !hostedZoneNameReverse.some((n, i) => n !== domainNameReverse[i]);
                }
                return false;
            })
                .sort((zone1, zone2) => zone2.Name.length - zone1.Name.length)
                .shift();
            return targetHostedZone;
        });
    }
```

I can see that I have hostedZone values but the if statement to assess the length fails as this array has two values (["com", "my-domain"].

Let me know if I output anything else to assist.
