### ISSUE TITLE
Certificate in the wrong region

### ISSUE THREAD

**Issue by danielbayerlein** [pfulop/serverless-cloudfront-distribution-certificate#2]
Edge-optimized endpoints require that the certificate be located in `us-east-1`. 
If another default region is configured, the certificate is created in the default region instead of `us-east-1`.

**Example:**

```yaml
provider:
  name: aws
  region: eu-central-1
```
