### ISSUE TITLE
SubjectAlternativeNames: failed to satisfy constraint

### ISSUE THREAD

**Issue by ron-johnson** [pfulop/serverless-cloudfront-distribution-certificate#7]
I am getting the error below when I use the following contraints:

```
custom:
  cfdDomain:
    domainName: ${self:custom.stage}.somesite.com
    cloudFront: CloudFrontWebDistribution
```

**Error**
```
Serverless: requesting certificate
 
  Validation Exception -----------------------------------
 
  1 validation error detected: Value '[]' at 'subjectAlternativeNames' failed to satisfy constraint: Member must have length greater than or equal to 1
``` 

We are on v0.0.4 and we have no desire to set a SAN for our cert. We initially used the domainNames parameter but that caused even more issues trying to pass in just a single domain.
